// Generated by tools/generate_sdk.mjs from Rust JSON Schema. Do not edit.
export namespace AngularVelocitySchema {
  export type Root = { "angular": [number, number, number] };
}
export type AngularVelocity = AngularVelocitySchema.Root;

export namespace CameraSchema {
  export type Root = { "far": number; "fov_degrees": number; "near": number };
}
export type Camera = CameraSchema.Root;

export namespace ColliderSchema {
  export type ColliderPart = { "id": string; "rotation": [number, number, number, number]; "shape": PrimitiveColliderShape; "translation": [number, number, number] };
  export type ColliderShape = ({ "half_extents": [number, number, number]; "type": "box" }) | ({ "radius": number; "type": "sphere" }) | ({ "half_height": number; "radius": number; "type": "capsule" }) | ({ "parts": Array<ColliderPart>; "type": "compound" });
  export type PrimitiveColliderShape = ({ "half_extents": [number, number, number]; "type": "box" }) | ({ "radius": number; "type": "sphere" }) | ({ "half_height": number; "radius": number; "type": "capsule" });
  export type Root = { "density": number; "filter": number; "friction": number; "memberships": number; "restitution": number; "sensor": boolean; "shape": ColliderShape };
}
export type Collider = ColliderSchema.Root;

export namespace CommandSchema {
  export type Asset = { "id": string; "import_settings"?: (AssetImportSettings) | (null); "kind": string; "name": string; "path": string; "sha256": string };
  export type AssetImportSettings = ({ "type": "texture"; "usage": TextureUsage });
  export type Entity = { "components": { [key: string]: unknown }; "id": string; "name": string; "parent"?: string | null; "provenance"?: (Provenance) | (null) };
  export type Origin = "user" | "agent" | "script" | "import";
  export type Provenance = { "actor": string; "conversation_id"?: string | null; "model"?: string | null; "origin": Origin; "transaction": string };
  export type Scene = { "entities": { [key: string]: Entity }; "id": string; "name": string };
  export type TextureUsage = "color" | "linear" | "normal";
  export type Root = ({ "op": "create_scene"; "scene": Scene }) | ({ "op": "delete_scene"; "scene_id": string }) | ({ "entity": Entity; "op": "create_entity"; "scene_id": string }) | ({ "entity_id": string; "op": "delete_entity"; "scene_id": string }) | ({ "entity_id": string; "name": string; "op": "rename_entity"; "scene_id": string }) | ({ "entity_id": string; "op": "reparent_entity"; "parent"?: string | null; "scene_id": string }) | ({ "component": string; "entity_id": string; "op": "set_component"; "scene_id": string; "value": unknown }) | ({ "component": string; "entity_id": string; "op": "remove_component"; "scene_id": string }) | ({ "asset": Asset; "op": "upsert_asset" }) | ({ "asset_id": string; "op": "remove_asset" }) | ({ "op": "set_memory"; "section": string; "text": string });
}
export type Command = CommandSchema.Root;

export namespace DirectionalLightSchema {
  export type DirectionalShadows = { "distance": number };
  export type Root = { "color": [number, number, number]; "intensity": number; "shadows"?: (DirectionalShadows) | (null) };
}
export type DirectionalLight = DirectionalLightSchema.Root;

export namespace EnvironmentLightSchema {
  export type Root = { "intensity": number; "rotation_degrees": number; "texture": string };
}
export type EnvironmentLight = EnvironmentLightSchema.Root;

export namespace GameSaveSchema {
  export type Asset = { "id": string; "import_settings"?: (AssetImportSettings) | (null); "kind": string; "name": string; "path": string; "sha256": string };
  export type AssetImportSettings = ({ "type": "texture"; "usage": TextureUsage });
  export type Entity = { "components": { [key: string]: unknown }; "id": string; "name": string; "parent"?: string | null; "provenance"?: (Provenance) | (null) };
  export type Origin = "user" | "agent" | "script" | "import";
  export type Project = { "assets": { [key: string]: Asset }; "id": string; "memory": { [key: string]: string }; "name": string; "scenes": { [key: string]: Scene }; "schema_version": number; "scripts": { [key: string]: ScriptSource }; "settings": ProjectSettings };
  export type ProjectSettings = { "tick_rate": number };
  export type Provenance = { "actor": string; "conversation_id"?: string | null; "model"?: string | null; "origin": Origin; "transaction": string };
  export type Scene = { "entities": { [key: string]: Entity }; "id": string; "name": string };
  export type Schedule = { "clock": ScriptClock; "timers": { [key: string]: Timer } };
  export type ScriptClock = { "elapsed_seconds": number; "tick": number };
  export type ScriptSource = { "id": string; "name": string; "path": string };
  export type TextureUsage = "color" | "linear" | "normal";
  export type Timer = { "due_tick": number; "interval_ticks"?: number | null; "payload": unknown };
  export type Root = { "authored_sha256": string; "elapsed_seconds": number; "format": string; "project": Project; "schedule"?: (Schedule) | (null); "script_sha256": string; "script_state": unknown; "tick": number; "version": number };
}
export type GameSave = GameSaveSchema.Root;

export namespace InputEventSchema {
  export type GamepadAxis = "left_x" | "left_y" | "right_x" | "right_y";
  export type GamepadButton = "south" | "east" | "west" | "north" | "left_shoulder" | "right_shoulder" | "left_trigger" | "right_trigger" | "select" | "start" | "guide" | "left_stick" | "right_stick" | "dpad_up" | "dpad_down" | "dpad_left" | "dpad_right";
  export type KeyCode = "KeyA" | "KeyB" | "KeyC" | "KeyD" | "KeyE" | "KeyF" | "KeyG" | "KeyH" | "KeyI" | "KeyJ" | "KeyK" | "KeyL" | "KeyM" | "KeyN" | "KeyO" | "KeyP" | "KeyQ" | "KeyR" | "KeyS" | "KeyT" | "KeyU" | "KeyV" | "KeyW" | "KeyX" | "KeyY" | "KeyZ" | "Digit0" | "Digit1" | "Digit2" | "Digit3" | "Digit4" | "Digit5" | "Digit6" | "Digit7" | "Digit8" | "Digit9" | "ArrowUp" | "ArrowDown" | "ArrowLeft" | "ArrowRight" | "Space" | "Enter" | "Escape" | "Tab" | "Backspace" | "Delete" | "Insert" | "Home" | "End" | "PageUp" | "PageDown" | "ShiftLeft" | "ShiftRight" | "ControlLeft" | "ControlRight" | "AltLeft" | "AltRight" | "MetaLeft" | "MetaRight" | "CapsLock" | "NumLock" | "ScrollLock" | "Pause" | "PrintScreen" | "ContextMenu" | "Backquote" | "Minus" | "Equal" | "BracketLeft" | "BracketRight" | "Backslash" | "Semicolon" | "Quote" | "Comma" | "Period" | "Slash" | "Numpad0" | "Numpad1" | "Numpad2" | "Numpad3" | "Numpad4" | "Numpad5" | "Numpad6" | "Numpad7" | "Numpad8" | "Numpad9" | "NumpadAdd" | "NumpadSubtract" | "NumpadMultiply" | "NumpadDivide" | "NumpadDecimal" | "NumpadEnter" | "F1" | "F2" | "F3" | "F4" | "F5" | "F6" | "F7" | "F8" | "F9" | "F10" | "F11" | "F12";
  export type MouseButton = "left" | "right" | "middle" | "back" | "forward";
  export type TouchPhase = "down" | "move" | "up" | "cancel";
  export type WheelUnit = "pixels" | "lines";
  export type Root = ({ "focused": boolean; "type": "focus" }) | ({ "code": KeyCode; "down": boolean; "type": "key" }) | ({ "button": MouseButton; "down": boolean; "type": "mouse_button" }) | ({ "position": [number, number]; "type": "pointer_position" }) | ({ "delta": [number, number]; "type": "pointer_motion" }) | ({ "delta": [number, number]; "type": "wheel"; "unit": WheelUnit }) | ({ "id": number; "type": "gamepad_connected" }) | ({ "id": number; "type": "gamepad_disconnected" }) | ({ "button": GamepadButton; "id": number; "type": "gamepad_button"; "value": number }) | ({ "axis": GamepadAxis; "id": number; "type": "gamepad_axis"; "value": number }) | ({ "id": number; "phase": TouchPhase; "position": [number, number]; "type": "touch" });
}
export type InputEvent = InputEventSchema.Root;

export namespace InputFrameSchema {
  export type Buttons = { "held": Array<KeyCode>; "pressed": Array<KeyCode>; "released": Array<KeyCode> };
  export type Buttons2 = { "held": Array<MouseButton>; "pressed": Array<MouseButton>; "released": Array<MouseButton> };
  export type Buttons3 = { "held": Array<GamepadButton>; "pressed": Array<GamepadButton>; "released": Array<GamepadButton> };
  export type GamepadButton = "south" | "east" | "west" | "north" | "left_shoulder" | "right_shoulder" | "left_trigger" | "right_trigger" | "select" | "start" | "guide" | "left_stick" | "right_stick" | "dpad_up" | "dpad_down" | "dpad_left" | "dpad_right";
  export type GamepadFrame = { "buttons": Buttons3; "left_stick": [number, number]; "right_stick": [number, number]; "values": { "dpad_down"?: number; "dpad_left"?: number; "dpad_right"?: number; "dpad_up"?: number; "east"?: number; "guide"?: number; "left_shoulder"?: number; "left_stick"?: number; "left_trigger"?: number; "north"?: number; "right_shoulder"?: number; "right_stick"?: number; "right_trigger"?: number; "select"?: number; "south"?: number; "start"?: number; "west"?: number } };
  export type Gesture = ({ "id": number; "position": [number, number]; "type": "tap" }) | ({ "id": number; "position": [number, number]; "type": "long_press" }) | ({ "direction": [number, number]; "distance": number; "duration_seconds": number; "id": number; "type": "swipe" }) | ({ "center": [number, number]; "ids": [number, number]; "rotation_delta": number; "scale_delta": number; "type": "pinch" });
  export type KeyCode = "KeyA" | "KeyB" | "KeyC" | "KeyD" | "KeyE" | "KeyF" | "KeyG" | "KeyH" | "KeyI" | "KeyJ" | "KeyK" | "KeyL" | "KeyM" | "KeyN" | "KeyO" | "KeyP" | "KeyQ" | "KeyR" | "KeyS" | "KeyT" | "KeyU" | "KeyV" | "KeyW" | "KeyX" | "KeyY" | "KeyZ" | "Digit0" | "Digit1" | "Digit2" | "Digit3" | "Digit4" | "Digit5" | "Digit6" | "Digit7" | "Digit8" | "Digit9" | "ArrowUp" | "ArrowDown" | "ArrowLeft" | "ArrowRight" | "Space" | "Enter" | "Escape" | "Tab" | "Backspace" | "Delete" | "Insert" | "Home" | "End" | "PageUp" | "PageDown" | "ShiftLeft" | "ShiftRight" | "ControlLeft" | "ControlRight" | "AltLeft" | "AltRight" | "MetaLeft" | "MetaRight" | "CapsLock" | "NumLock" | "ScrollLock" | "Pause" | "PrintScreen" | "ContextMenu" | "Backquote" | "Minus" | "Equal" | "BracketLeft" | "BracketRight" | "Backslash" | "Semicolon" | "Quote" | "Comma" | "Period" | "Slash" | "Numpad0" | "Numpad1" | "Numpad2" | "Numpad3" | "Numpad4" | "Numpad5" | "Numpad6" | "Numpad7" | "Numpad8" | "Numpad9" | "NumpadAdd" | "NumpadSubtract" | "NumpadMultiply" | "NumpadDivide" | "NumpadDecimal" | "NumpadEnter" | "F1" | "F2" | "F3" | "F4" | "F5" | "F6" | "F7" | "F8" | "F9" | "F10" | "F11" | "F12";
  export type MouseButton = "left" | "right" | "middle" | "back" | "forward";
  export type MouseFrame = { "buttons": Buttons2; "motion": [number, number]; "position"?: [number, number] | null; "wheel_lines": [number, number]; "wheel_pixels": [number, number] };
  export type TouchChange = { "id": number; "phase": TouchPhase; "position": [number, number] };
  export type TouchPhase = "down" | "move" | "up" | "cancel";
  export type TouchPoint = { "delta": [number, number]; "position": [number, number] };
  export type Root = { "connected": Array<number>; "disconnected": Array<number>; "focused": boolean; "gamepads": { [key: number]: GamepadFrame | undefined }; "gestures": Array<Gesture>; "keyboard": Buttons; "mouse": MouseFrame; "touch_changes": Array<TouchChange>; "touches": { [key: number]: TouchPoint | undefined } };
}
export type InputFrame = InputFrameSchema.Root;

export namespace InputRecordingSchema {
  export type GamepadAxis = "left_x" | "left_y" | "right_x" | "right_y";
  export type GamepadButton = "south" | "east" | "west" | "north" | "left_shoulder" | "right_shoulder" | "left_trigger" | "right_trigger" | "select" | "start" | "guide" | "left_stick" | "right_stick" | "dpad_up" | "dpad_down" | "dpad_left" | "dpad_right";
  export type InputEvent = ({ "focused": boolean; "type": "focus" }) | ({ "code": KeyCode; "down": boolean; "type": "key" }) | ({ "button": MouseButton; "down": boolean; "type": "mouse_button" }) | ({ "position": [number, number]; "type": "pointer_position" }) | ({ "delta": [number, number]; "type": "pointer_motion" }) | ({ "delta": [number, number]; "type": "wheel"; "unit": WheelUnit }) | ({ "id": number; "type": "gamepad_connected" }) | ({ "id": number; "type": "gamepad_disconnected" }) | ({ "button": GamepadButton; "id": number; "type": "gamepad_button"; "value": number }) | ({ "axis": GamepadAxis; "id": number; "type": "gamepad_axis"; "value": number }) | ({ "id": number; "phase": TouchPhase; "position": [number, number]; "type": "touch" });
  export type KeyCode = "KeyA" | "KeyB" | "KeyC" | "KeyD" | "KeyE" | "KeyF" | "KeyG" | "KeyH" | "KeyI" | "KeyJ" | "KeyK" | "KeyL" | "KeyM" | "KeyN" | "KeyO" | "KeyP" | "KeyQ" | "KeyR" | "KeyS" | "KeyT" | "KeyU" | "KeyV" | "KeyW" | "KeyX" | "KeyY" | "KeyZ" | "Digit0" | "Digit1" | "Digit2" | "Digit3" | "Digit4" | "Digit5" | "Digit6" | "Digit7" | "Digit8" | "Digit9" | "ArrowUp" | "ArrowDown" | "ArrowLeft" | "ArrowRight" | "Space" | "Enter" | "Escape" | "Tab" | "Backspace" | "Delete" | "Insert" | "Home" | "End" | "PageUp" | "PageDown" | "ShiftLeft" | "ShiftRight" | "ControlLeft" | "ControlRight" | "AltLeft" | "AltRight" | "MetaLeft" | "MetaRight" | "CapsLock" | "NumLock" | "ScrollLock" | "Pause" | "PrintScreen" | "ContextMenu" | "Backquote" | "Minus" | "Equal" | "BracketLeft" | "BracketRight" | "Backslash" | "Semicolon" | "Quote" | "Comma" | "Period" | "Slash" | "Numpad0" | "Numpad1" | "Numpad2" | "Numpad3" | "Numpad4" | "Numpad5" | "Numpad6" | "Numpad7" | "Numpad8" | "Numpad9" | "NumpadAdd" | "NumpadSubtract" | "NumpadMultiply" | "NumpadDivide" | "NumpadDecimal" | "NumpadEnter" | "F1" | "F2" | "F3" | "F4" | "F5" | "F6" | "F7" | "F8" | "F9" | "F10" | "F11" | "F12";
  export type MouseButton = "left" | "right" | "middle" | "back" | "forward";
  export type RecordedTick = { "events": Array<InputEvent>; "tick": number };
  export type TouchPhase = "down" | "move" | "up" | "cancel";
  export type WheelUnit = "pixels" | "lines";
  export type Root = { "format": string; "frames": Array<RecordedTick>; "start_tick": number; "tick_rate": number; "ticks": number; "version": number };
}
export type InputRecording = InputRecordingSchema.Root;

export namespace MeshRendererSchema {
  export type Root = { "cast_shadows": boolean; "materials": Array<string>; "mesh": string };
}
export type MeshRenderer = MeshRendererSchema.Root;

export namespace PhysicsCharacterMovementSchema {
  export type Root = { "collisions": Array<string>; "grounded": boolean; "sliding_down_slope": boolean; "translation": [number, number, number] };
}
export type PhysicsCharacterMovement = PhysicsCharacterMovementSchema.Root;

export namespace PhysicsCharacterQuerySchema {
  export type CharacterOptions = { "autostep"?: (CharacterStep) | (null); "max_slope_climb_angle": number; "min_slope_slide_angle": number; "offset": number; "slide": boolean; "snap_to_ground"?: number | null };
  export type CharacterStep = { "include_dynamic_bodies": boolean; "max_height": number; "min_width": number };
  export type Root = { "entity_id": string; "options"?: CharacterOptions; "scene_id": string; "translation": [number, number, number] };
}
export type PhysicsCharacterQuery = PhysicsCharacterQuerySchema.Root;

export namespace PhysicsRayHitSchema {
  export type Root = { "distance": number; "entity_id": string; "normal": [number, number, number]; "point": [number, number, number] };
}
export type PhysicsRayHit = PhysicsRayHitSchema.Root;

export namespace PhysicsRayQuerySchema {
  export type Root = { "direction": [number, number, number]; "exclude_entity"?: string | null; "filter": number; "include_sensors": boolean; "max_distance": number; "memberships": number; "origin": [number, number, number]; "scene_id": string };
}
export type PhysicsRayQuery = PhysicsRayQuerySchema.Root;

export namespace PhysicsTriggerEventSchema {
  export type Root = { "entered": boolean; "first": string; "scene_id": string; "second": string };
}
export type PhysicsTriggerEvent = PhysicsTriggerEventSchema.Root;

export namespace PlayAssertionsSchema {
  export type Check = { "expect": Expect; "name": string; "path": string; "tick": number };
  export type Expect = ({ "type": "equals"; "value": unknown }) | ({ "tolerance": number; "type": "approx"; "value": number }) | ({ "max": number; "min": number; "type": "range" }) | ({ "exists": boolean; "type": "exists" });
  export type Root = { "checks": Array<Check>; "format": string; "version": number };
}
export type PlayAssertions = PlayAssertionsSchema.Root;

export namespace PointLightSchema {
  export type Root = { "color": [number, number, number]; "intensity": number; "range": number };
}
export type PointLight = PointLightSchema.Root;

export namespace ProjectSchema {
  export type Asset = { "id": string; "import_settings"?: (AssetImportSettings) | (null); "kind": string; "name": string; "path": string; "sha256": string };
  export type AssetImportSettings = ({ "type": "texture"; "usage": TextureUsage });
  export type Entity = { "components": { [key: string]: unknown }; "id": string; "name": string; "parent"?: string | null; "provenance"?: (Provenance) | (null) };
  export type Origin = "user" | "agent" | "script" | "import";
  export type ProjectSettings = { "tick_rate": number };
  export type Provenance = { "actor": string; "conversation_id"?: string | null; "model"?: string | null; "origin": Origin; "transaction": string };
  export type Scene = { "entities": { [key: string]: Entity }; "id": string; "name": string };
  export type ScriptSource = { "id": string; "name": string; "path": string };
  export type TextureUsage = "color" | "linear" | "normal";
  export type Root = { "assets": { [key: string]: Asset }; "id": string; "memory": { [key: string]: string }; "name": string; "scenes": { [key: string]: Scene }; "schema_version": number; "scripts": { [key: string]: ScriptSource }; "settings": ProjectSettings };
}
export type Project = ProjectSchema.Root;

export namespace RigidBodySchema {
  export type BodyMotion = "fixed" | "dynamic" | "kinematic";
  export type Root = { "angular_damping": number; "can_sleep": boolean; "ccd": boolean; "gravity_scale": number; "linear_damping": number; "motion": BodyMotion };
}
export type RigidBody = RigidBodySchema.Root;

export namespace ScriptSchema {
  export type Root = { "props": { [key: string]: unknown }; "source": string };
}
export type Script = ScriptSchema.Root;

export namespace ScriptClockSchema {
  export type Root = { "elapsed_seconds": number; "tick": number };
}
export type ScriptClock = ScriptClockSchema.Root;

export namespace SpotLightSchema {
  export type Root = { "color": [number, number, number]; "inner_degrees": number; "intensity": number; "outer_degrees": number; "range": number };
}
export type SpotLight = SpotLightSchema.Root;

export namespace TimerEventSchema {
  export type Root = { "id": string; "payload": unknown; "scheduled_tick": number };
}
export type TimerEvent = TimerEventSchema.Root;

export namespace TimerRequestSchema {
  export type Root = { "delay_ticks": number; "id": string; "interval_ticks"?: number | null; "payload"?: unknown };
}
export type TimerRequest = TimerRequestSchema.Root;

export namespace TransformSchema {
  export type Root = { "rotation": [number, number, number, number]; "scale": [number, number, number]; "translation": [number, number, number] };
}
export type Transform = TransformSchema.Root;

export namespace VelocitySchema {
  export type Root = { "linear": [number, number, number] };
}
export type Velocity = VelocitySchema.Root;
