// Generated by tools/generate_sdk.mjs from Rust JSON Schema. Do not edit.
export namespace AngularVelocitySchema {
  export type Root = { "angular": [number, number, number] };
}
export type AngularVelocity = AngularVelocitySchema.Root;

export namespace CameraSchema {
  export type Root = { "far": number; "fov_degrees": number; "near": number };
}
export type Camera = CameraSchema.Root;

export namespace ColliderSchema {
  export type ColliderShape = ({ "half_extents": [number, number, number]; "type": "box" }) | ({ "radius": number; "type": "sphere" }) | ({ "half_height": number; "radius": number; "type": "capsule" });
  export type Root = { "density": number; "filter": number; "friction": number; "memberships": number; "restitution": number; "sensor": boolean; "shape": ColliderShape };
}
export type Collider = ColliderSchema.Root;

export namespace CommandSchema {
  export type Asset = { "id": string; "import_settings"?: (AssetImportSettings) | (null); "kind": string; "name": string; "path": string; "sha256": string };
  export type AssetImportSettings = ({ "type": "texture"; "usage": TextureUsage });
  export type Entity = { "components": { [key: string]: unknown }; "id": string; "name": string; "parent"?: string | null; "provenance"?: (Provenance) | (null) };
  export type Origin = "user" | "agent" | "script" | "import";
  export type Provenance = { "actor": string; "conversation_id"?: string | null; "model"?: string | null; "origin": Origin; "transaction": string };
  export type Scene = { "entities": { [key: string]: Entity }; "id": string; "name": string };
  export type TextureUsage = "color" | "linear" | "normal";
  export type Root = ({ "op": "create_scene"; "scene": Scene }) | ({ "op": "delete_scene"; "scene_id": string }) | ({ "entity": Entity; "op": "create_entity"; "scene_id": string }) | ({ "entity_id": string; "op": "delete_entity"; "scene_id": string }) | ({ "entity_id": string; "name": string; "op": "rename_entity"; "scene_id": string }) | ({ "entity_id": string; "op": "reparent_entity"; "parent"?: string | null; "scene_id": string }) | ({ "component": string; "entity_id": string; "op": "set_component"; "scene_id": string; "value": unknown }) | ({ "component": string; "entity_id": string; "op": "remove_component"; "scene_id": string }) | ({ "asset": Asset; "op": "upsert_asset" }) | ({ "asset_id": string; "op": "remove_asset" }) | ({ "op": "set_memory"; "section": string; "text": string });
}
export type Command = CommandSchema.Root;

export namespace DirectionalLightSchema {
  export type DirectionalShadows = { "distance": number };
  export type Root = { "color": [number, number, number]; "intensity": number; "shadows"?: (DirectionalShadows) | (null) };
}
export type DirectionalLight = DirectionalLightSchema.Root;

export namespace EnvironmentLightSchema {
  export type Root = { "intensity": number; "rotation_degrees": number; "texture": string };
}
export type EnvironmentLight = EnvironmentLightSchema.Root;

export namespace GameSaveSchema {
  export type Asset = { "id": string; "import_settings"?: (AssetImportSettings) | (null); "kind": string; "name": string; "path": string; "sha256": string };
  export type AssetImportSettings = ({ "type": "texture"; "usage": TextureUsage });
  export type Entity = { "components": { [key: string]: unknown }; "id": string; "name": string; "parent"?: string | null; "provenance"?: (Provenance) | (null) };
  export type Origin = "user" | "agent" | "script" | "import";
  export type Project = { "assets": { [key: string]: Asset }; "id": string; "memory": { [key: string]: string }; "name": string; "scenes": { [key: string]: Scene }; "schema_version": number; "scripts": { [key: string]: ScriptSource }; "settings": ProjectSettings };
  export type ProjectSettings = { "tick_rate": number };
  export type Provenance = { "actor": string; "conversation_id"?: string | null; "model"?: string | null; "origin": Origin; "transaction": string };
  export type Scene = { "entities": { [key: string]: Entity }; "id": string; "name": string };
  export type ScriptSource = { "id": string; "name": string; "path": string };
  export type TextureUsage = "color" | "linear" | "normal";
  export type Root = { "authored_sha256": string; "elapsed_seconds": number; "format": string; "project": Project; "script_sha256": string; "script_state": unknown; "tick": number; "version": number };
}
export type GameSave = GameSaveSchema.Root;

export namespace MeshRendererSchema {
  export type Root = { "cast_shadows": boolean; "materials": Array<string>; "mesh": string };
}
export type MeshRenderer = MeshRendererSchema.Root;

export namespace PhysicsCharacterMovementSchema {
  export type Root = { "collisions": Array<string>; "grounded": boolean; "sliding_down_slope": boolean; "translation": [number, number, number] };
}
export type PhysicsCharacterMovement = PhysicsCharacterMovementSchema.Root;

export namespace PhysicsCharacterQuerySchema {
  export type CharacterOptions = { "autostep"?: (CharacterStep) | (null); "max_slope_climb_angle": number; "min_slope_slide_angle": number; "offset": number; "slide": boolean; "snap_to_ground"?: number | null };
  export type CharacterStep = { "include_dynamic_bodies": boolean; "max_height": number; "min_width": number };
  export type Root = { "entity_id": string; "options"?: CharacterOptions; "scene_id": string; "translation": [number, number, number] };
}
export type PhysicsCharacterQuery = PhysicsCharacterQuerySchema.Root;

export namespace PhysicsRayHitSchema {
  export type Root = { "distance": number; "entity_id": string; "normal": [number, number, number]; "point": [number, number, number] };
}
export type PhysicsRayHit = PhysicsRayHitSchema.Root;

export namespace PhysicsRayQuerySchema {
  export type Root = { "direction": [number, number, number]; "exclude_entity"?: string | null; "filter": number; "include_sensors": boolean; "max_distance": number; "memberships": number; "origin": [number, number, number]; "scene_id": string };
}
export type PhysicsRayQuery = PhysicsRayQuerySchema.Root;

export namespace PhysicsTriggerEventSchema {
  export type Root = { "entered": boolean; "first": string; "scene_id": string; "second": string };
}
export type PhysicsTriggerEvent = PhysicsTriggerEventSchema.Root;

export namespace PointLightSchema {
  export type Root = { "color": [number, number, number]; "intensity": number; "range": number };
}
export type PointLight = PointLightSchema.Root;

export namespace ProjectSchema {
  export type Asset = { "id": string; "import_settings"?: (AssetImportSettings) | (null); "kind": string; "name": string; "path": string; "sha256": string };
  export type AssetImportSettings = ({ "type": "texture"; "usage": TextureUsage });
  export type Entity = { "components": { [key: string]: unknown }; "id": string; "name": string; "parent"?: string | null; "provenance"?: (Provenance) | (null) };
  export type Origin = "user" | "agent" | "script" | "import";
  export type ProjectSettings = { "tick_rate": number };
  export type Provenance = { "actor": string; "conversation_id"?: string | null; "model"?: string | null; "origin": Origin; "transaction": string };
  export type Scene = { "entities": { [key: string]: Entity }; "id": string; "name": string };
  export type ScriptSource = { "id": string; "name": string; "path": string };
  export type TextureUsage = "color" | "linear" | "normal";
  export type Root = { "assets": { [key: string]: Asset }; "id": string; "memory": { [key: string]: string }; "name": string; "scenes": { [key: string]: Scene }; "schema_version": number; "scripts": { [key: string]: ScriptSource }; "settings": ProjectSettings };
}
export type Project = ProjectSchema.Root;

export namespace RigidBodySchema {
  export type BodyMotion = "fixed" | "dynamic" | "kinematic";
  export type Root = { "angular_damping": number; "can_sleep": boolean; "ccd": boolean; "gravity_scale": number; "linear_damping": number; "motion": BodyMotion };
}
export type RigidBody = RigidBodySchema.Root;

export namespace ScriptSchema {
  export type Root = { "props": { [key: string]: unknown }; "source": string };
}
export type Script = ScriptSchema.Root;

export namespace SpotLightSchema {
  export type Root = { "color": [number, number, number]; "inner_degrees": number; "intensity": number; "outer_degrees": number; "range": number };
}
export type SpotLight = SpotLightSchema.Root;

export namespace TransformSchema {
  export type Root = { "rotation": [number, number, number, number]; "scale": [number, number, number]; "translation": [number, number, number] };
}
export type Transform = TransformSchema.Root;

export namespace VelocitySchema {
  export type Root = { "linear": [number, number, number] };
}
export type Velocity = VelocitySchema.Root;
