// Generated by tools/generate_sdk.mjs from Rust JSON Schema. Do not edit.
export namespace CameraSchema {
  export type Root = { "far": number; "fov_degrees": number; "near": number };
}
export type Camera = CameraSchema.Root;

export namespace CommandSchema {
  export type Entity = { "components": { [key: string]: unknown }; "id": string; "name": string; "parent"?: string | null; "provenance"?: (Provenance) | (null) };
  export type Origin = "user" | "agent" | "script" | "import";
  export type Provenance = { "actor": string; "conversation_id"?: string | null; "model"?: string | null; "origin": Origin; "transaction": string };
  export type Scene = { "entities": { [key: string]: Entity }; "id": string; "name": string };
  export type Root = ({ "op": "create_scene"; "scene": Scene }) | ({ "op": "delete_scene"; "scene_id": string }) | ({ "entity": Entity; "op": "create_entity"; "scene_id": string }) | ({ "entity_id": string; "op": "delete_entity"; "scene_id": string }) | ({ "entity_id": string; "name": string; "op": "rename_entity"; "scene_id": string }) | ({ "entity_id": string; "op": "reparent_entity"; "parent"?: string | null; "scene_id": string }) | ({ "component": string; "entity_id": string; "op": "set_component"; "scene_id": string; "value": unknown }) | ({ "component": string; "entity_id": string; "op": "remove_component"; "scene_id": string }) | ({ "op": "set_memory"; "section": string; "text": string });
}
export type Command = CommandSchema.Root;

export namespace MeshRendererSchema {
  export type Root = { "cast_shadows": boolean; "materials": Array<string>; "mesh": string };
}
export type MeshRenderer = MeshRendererSchema.Root;

export namespace ProjectSchema {
  export type Asset = { "id": string; "kind": string; "name": string; "path": string; "sha256": string };
  export type Entity = { "components": { [key: string]: unknown }; "id": string; "name": string; "parent"?: string | null; "provenance"?: (Provenance) | (null) };
  export type Origin = "user" | "agent" | "script" | "import";
  export type ProjectSettings = { "tick_rate": number };
  export type Provenance = { "actor": string; "conversation_id"?: string | null; "model"?: string | null; "origin": Origin; "transaction": string };
  export type Scene = { "entities": { [key: string]: Entity }; "id": string; "name": string };
  export type ScriptSource = { "id": string; "name": string; "path": string };
  export type Root = { "assets": { [key: string]: Asset }; "id": string; "memory": { [key: string]: string }; "name": string; "scenes": { [key: string]: Scene }; "schema_version": number; "scripts": { [key: string]: ScriptSource }; "settings": ProjectSettings };
}
export type Project = ProjectSchema.Root;

export namespace ScriptSchema {
  export type Root = { "props": { [key: string]: unknown }; "source": string };
}
export type Script = ScriptSchema.Root;

export namespace TransformSchema {
  export type Root = { "rotation": [number, number, number, number]; "scale": [number, number, number]; "translation": [number, number, number] };
}
export type Transform = TransformSchema.Root;

export namespace VelocitySchema {
  export type Root = { "linear": [number, number, number] };
}
export type Velocity = VelocitySchema.Root;
