[package]
name = "incant_localization"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
thiserror.workspace = true
ulid.workspace = true
icu_locale = { version = "=2.3.0", default-features = false }
icu_decimal = "=2.3.0"
icu_datetime = { version = "=2.3.0", default-features = false, features = ["compiled_data"] }
icu_plurals = "=2.3.0"
writeable = "=0.6.4"
