[package]
name = "incant_platform_smoke"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
incant_doc = { workspace = true }
incant_core = { workspace = true }
incant_input.workspace = true
incant_localization.workspace = true
serde_json = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "=0.2.126"
