[package]
name = "incant_core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
incant_nav.workspace = true
schemars.workspace = true
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
incant_doc = { workspace = true }
incant_physics.workspace = true
glam = "0.32"

[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy_app = { workspace = true, features = ["web"] }
