#!/usr/bin/env node
/** Compile the host-injected transport; no UI layout or engine state is bundled here. */
import { transformFile } from "@swc/core";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
const root = resolve(import.meta.dirname, "..");
const result = await transformFile(resolve(root, "editor/bridge/native.ts"), {
  jsc: { parser: { syntax: "typescript" }, target: "es2022" },
  module: { type: "commonjs", strict: true },
  sourceMaps: false,
});
const code =
  "// Generated by tools/build_bridge.mjs. Do not edit.\n(function(exports) {\n" +
  result.code +
  "\nexports.installNativeBridge();\n})({});\n";
const output = resolve(root, "editor/bridge/native.generated.js");
if (process.argv.includes("--check")) {
  if ((await readFile(output, "utf8")) !== code)
    throw new Error("Native bridge is stale");
} else await writeFile(output, code);
