#!/usr/bin/env node
/** Generate the SDK's structural types from the Rust-derived published registry. */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const root=resolve(import.meta.dirname,'..');
const quote=JSON.stringify;
function type(s) {
  if(s===true || Object.keys(s).length===0) return 'unknown';
  if(s===false) return 'never';
  if(s.$ref) {
    if(!s.$ref.startsWith('#/$defs/')) throw new Error(`Unsupported external ref: ${s.$ref}`);
    return s.$ref.slice(8);
  }
  if(s.const!==undefined) return quote(s.const);
  if(s.enum) return s.enum.map(quote).join(' | ');
  if(s.oneOf || s.anyOf) return (s.oneOf ?? s.anyOf).map(x=>`(${type(x)})`).join(' | ');
  if(s.allOf) return s.allOf.map(x=>`(${type(x)})`).join(' & ');
  if(Array.isArray(s.type)) return s.type.map(t=>type({...s,type:t})).join(' | ');
  switch(s.type) {
    case 'string': return 'string';
    case 'number': case 'integer': return 'number';
    case 'boolean': return 'boolean';
    case 'null': return 'null';
    case 'array': {
      if(s.prefixItems) return `[${s.prefixItems.map(type).join(', ')}]`;
      if(Number.isInteger(s.minItems) && s.minItems===s.maxItems && s.maxItems<=32) return `[${Array(s.minItems).fill(type(s.items ?? true)).join(', ')}]`;
      return `Array<${type(s.items ?? true)}>`;
    }
    case 'object': {
      const fields=Object.entries(s.properties ?? {}).map(([key,value])=>`${quote(key)}${s.required?.includes(key)?'':'?'}: ${type(value)}`);
      if(s.additionalProperties && s.additionalProperties!==false) fields.push(`[key: string]: ${type(s.additionalProperties)}`);
      return `{ ${fields.join('; ')} }`;
    }
    case undefined: return 'unknown';
    default: throw new Error(`Unsupported schema type: ${s.type}`);
  }
}
let text='// Generated by tools/generate_sdk.mjs from Rust JSON Schema. Do not edit.\n';
for(const file of (await readdir(resolve(root,'schemas'))).filter(f=>f.endsWith('.schema.json')).sort()) {
  const name=file.slice(0,-12);
  if(!/^[A-Za-z][A-Za-z0-9]*$/.test(name)) throw new Error('Invalid schema name');
  const schema=JSON.parse(await readFile(resolve(root,'schemas',file),'utf8'));
  text+=`export namespace ${name}Schema {\n`;
  for(const [key,value] of Object.entries(schema.$defs ?? {}).sort(([a],[b])=>a.localeCompare(b))) text+=`  export type ${key} = ${type(value)};\n`;
  text+=`  export type Root = ${type(schema)};\n}\nexport type ${name} = ${name}Schema.Root;\n\n`;
}
const output=resolve(root,'sdk/ts/src/generated.d.ts');
text = text.trimEnd() + '\n';
if(process.argv.includes('--check')) {
  if(await readFile(output,'utf8')!==text) throw new Error('Generated SDK is stale');
} else await writeFile(output,text);
