#!/usr/bin/env python3
"""Generate both agent instruction files from the shared convention source."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, role in [('AGENTS.md', 'astra'), ('CLAUDE.md', 'claude')]:
        content = '<!-- Generated by tools/generate_conventions.py; edit docs/conventions/. -->\n\n'
        content += (ROOT / 'docs/conventions/shared.md').read_text()
        content += '\n' + (ROOT / f'docs/conventions/{role}.md').read_text()
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f'{name} is stale; run npm run conventions')
        else:
            path.write_text(content)

if __name__ == '__main__':
    main()
